### ISSUE TITLE
re-do user cards

### ISSUE THREAD

**Issue by CerryTsuki** [CerryTsuki/PlumCherry#7]
GOD DAMN IT DISCORD

**Comment by TailaBlu** [comment]
Hi! I’m really sorry if this isn’t how I’m supposed to contact you, I’m very new to GitHub and don’t know how to contact you otherwise. I wanted to let you know that I sorta-kinda got it working on BetterDiscord! I hope this is good news! ^^
![image](https://github.com/CerryTsuki/PlumCherry/assets/59271278/053b32a9-c3f3-40c9-ac5a-67bcc2f39577)
